routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\QuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
// Route::resource('question','QuestionController');
// Route::get('/quiz/{id}/questions','QuizControlle

// Route::get('/question/create', [QuestionController::class, 'create']);

Route::resource('question', QuestionController::class);

Route::get('dynamic', function () {
    return view('task.dynamic');
})->name('dynamic');

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $casts = [
        'answer' => 'string',
    ];

    public function question(){
        return $this->belongsTo(Question::class);
    }
}

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function answers(){
        return $this->hasMany(Answer::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::all();
        return view('task.question.index',compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('task.question.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $question = new Question;
        $question->question =$request->question;
        $question->save();

        foreach($request->options as $key=>$option){
            $is_correct =false;
            if($key==$request->correct_answer){
                $is_correct=true;
            }
            $answer = new Answer;
            $answer->question_id = $question->id;
            $answer->answer = $option;
            $answer->is_correct = $is_correct;
            $answer->save();
        }

        // \Storage::disk('local')->put($question,$answer);
        return redirect()->route('question.create')->with('message','Question created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $question = Question::with('answers')->where('id',$id)->first();
        // dd($question);
        return view('task.question.show',compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Question::where('id',$id)->delete();
        Answer::where('question_id',$id)->delete();
        return redirect()->route('question.index')->with('message','Question deleted successfully!');
    }

    public function validateForm($request){
        return $this->validate($request,[
            'quiz'=>'required',
            'question'=>'required',
            'options'=>'required|array|min:3',
            'options.*'=>'required|string|distinct',
            'correct_answer'=>'required'
        ]);
    }

}

resources/views/index.blade.php
@include('layouts.navbar')
<!-- /navbar -->
@include('layouts.sidebar')
            <!--/.span3-->
@include('layouts.dashboard')
<!--/.wrapper-->
@include('layouts.footer')

resources/views/layouts/footer.blade.php
<div class="footer">
    <div class="container">
        <b class="copyright">&copy; 2014 Edmin - EGrappler.com </b>All rights reserved.
    </div>
</div>
<script src="{{asset('admin/code')}}/scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="{{asset('admin/code')}}/scripts/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="{{asset('admin/code')}}/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="{{asset('admin/code')}}/scripts/flot/jquery.flot.js" type="text/javascript"></script>
<script src="{{asset('admin/code')}}/scripts/flot/jquery.flot.resize.js" type="text/javascript"></script>
<script src="{{asset('admin/code')}}/scripts/datatables/jquery.dataTables.js" type="text/javascript"></script>
<script src="{{asset('admin/code')}}/scripts/common.js" type="text/javascript"></script>

@yield('js')
</body>

resources/views/layouts/master.blade.php
@include('layouts.navbar')
@include('layouts.sidebar')

@yield('content')

@include('layouts.footer')

resources/views/layouts/navbar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Edmin</title>
        <link type="text/css" href="{{asset('admin/code')}}/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link type="text/css" href="{{asset('admin/code')}}/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
        <link type="text/css" href="{{asset('admin/code')}}/css/theme.css" rel="stylesheet">
        <link type="text/css" href="{{asset('admin/code')}}/images/icons/css/font-awesome.css" rel="stylesheet">
        <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
              rel='stylesheet'>
    </head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                <i class="icon-reorder shaded"></i></a><a class="brand" href="index.html">Edmin </a>
            <div class="nav-collapse collapse navbar-inverse-collapse">
                <ul class="nav nav-icons">
                    <li class="active"><a href="#"><i class="icon-envelope"></i></a></li>
                    <li><a href="#"><i class="icon-eye-open"></i></a></li>
                    <li><a href="#"><i class="icon-bar-chart"></i></a></li>
                </ul>
                <form class="navbar-search pull-left input-append" action="#">
                    <input type="text" class="span3">
                    <button class="btn" type="button">
                        <i class="icon-search"></i>
                    </button>
                </form>
                <ul class="nav pull-right">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown
                            <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Item No. 1</a></li>
                            <li><a href="#">Don't Click</a></li>
                            <li class="divider"></li>
                            <li class="nav-header">Example Header</li>
                            <li><a href="#">A Separated link</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Support </a></li>
                    <li class="nav-user dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{asset('admin/code')}}/images/user.png" class="nav-avatar" />
                            <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Your Profile</a></li>
                            <li><a href="#">Edit Profile</a></li>
                            <li><a href="#">Account Settings</a></li>
                            <li class="divider"></li>


                                

                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.nav-collapse -->
        </div>
    </div>
    <!-- /navbar-inner -->
</div>

resources/views/layouts/sidebar.blade.php
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="span3">
    <div class="sidebar">
        <ul class="widget widget-menu unstyled">

            <li><a href="{{route('question.create')}}"><i class="menu-icon icon-bullhorn"></i> Create Question </a>
            </li>
            <li><a href="{{route('question.index')}}"><i class="menu-icon icon-inbox"></i>View Question <b class="label green pull-right">
                    </b> </a></li>
            <li><a href="{{route('dynamic')}}"><i class="menu-icon icon-table"></i> Dynamic Form </a>

        </ul>

        
    </div>
    <!--/.sidebar-->
</div>

resources/views/task/dynamic.blade.php
@extends('layouts.master')

@section('title','create quiz')

@section('content')
<!-- <link rel="stylesheet" href= 
"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
	integrity= 
"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
	crossorigin="anonymous">  -->

 
<div class="span9">
    <div class="content">
        @if(Session::has('message'))
            <div class="alert alert-success">		
                {{Session::get('message')}}
            </div>
        @endif
        <div class="module">
            <div class="module-head">
                <h3>Dynamic Form</h3>
            </div>     
                <div class="module-body"> 
                    <table class="table table-bordered"> 
                        <thead> 
                        <tr> 
                            <th class="text-center">Row Number</th> 
                            <th class="text-center">Remove Row</th> 
                        </tr> 
                        
                        </thead> 
                        <tbody id="tbody"> 
                        <tr> 
                            <td class="text-center">Row 1</td> 
                            <td class="text-center"> 
                            <button class="btn btn-danger remove"
                            type="button">Remove</button> 
                            </td>
                        </tr>
                        <tr> 
                            <td class="text-center">Row 2</td> 
                            <td class="text-center"> 
                            <button class="btn btn-danger remove"
                            type="button">Remove</button> 
                            </td>
                        </tr>
                        </tbody> 
                    </table> 
                </div> 
                <button class="btn btn-md btn-primary"
                id="addBtn" type="button"> 
                    Add new Row 
                </button>  
    </div>
</div>            




<script src= 
"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> 
</script> 
<script src= 
"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> 
</script> 
<script src= 
"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> 
</script> 

<script> 
	$(document).ready(function () { 

	// Denotes total number of rows 
	var rowIdx = 2; 

	// jQuery button click event to add a row 
	$('#addBtn').on('click', function () { 

		// Adding a row inside the tbody. 
		$('#tbody').append(`<tr id="R${++rowIdx}"> 
			<td class="row-index text-center"> 
			<p>Row ${rowIdx}</p> 
			</td> 
			<td class="text-center"> 
				<button class="btn btn-danger remove"
				type="button">Remove</button> 
				</td> 
			</tr>`); 
	}); 

	$('#tbody').on('click', '.remove', function () { 

		var child = $(this).closest('tr').nextAll(); 

		child.each(function () { 
 
		var id = $(this).attr('id'); 

		var idx = $(this).children('.row-index').children('p'); 

		var dig = parseInt(id.substring(1)); 

		idx.html(`Row ${dig - 1}`); 

		$(this).attr('id', `R${dig - 1}`); 
		}); 

		$(this).closest('tr').remove(); 
		rowIdx--; 
	}); 
	}); 
</script>

@stop

resources/views/task/question/create.blade.php
@extends('layouts.master')

@section('title','create quiz')

@section('content')

    <div class="span9">
        <div class="content">

            @if(Session::has('message'))

                <div class="alert alert-success">{{Session::get('message')}}</div>
            @endif



            <form action="{{route('question.store')}}" method="POST">
                @csrf

                <div class="module">
                    <div class="module-head">
                        <h3>Create Question</h3>
                    </div>


                    <div class="module-body">
                        

                        <div class="control-group ml-l">
                            <label class="control-lable" for="name">Question name</label>
                            <div class="controls">
                                <input type="text" name="question" id="question" class="span8 @error('name') border-red @enderror" placeholder="name of a quiz" value=" {{old('questioin')}}   " >
                            </div>
                            @error('question')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror

                        </div>

                        <div class="control-group">
                            <label class="control-lable" for="options">Options</label>
                            <div class="controls">
                                @for($i=0 ; $i<4 ; $i++)
                                    <input type="text" id="option" name="options[]" class="span7 @error('name') border-red @enderror"
                                     placeholder=" options{{$i+1}}" required="">

                                    <input style="margin-left:5px ; margin-right:3px" type="radio" name="correct_answer" value="{{$i}}"><span class="ml-2">Is correct answer</span>
                                @endfor
                            </div>
                            @error('question')
                            <span class="invalid-feedback" role="alert">
			        <strong>{{ $message }}</strong>
			    </span>
                            @enderror

                        </div>

                        <div class="control-group">
                            <div class="controls">
                                <button type="submit" class="btn btn-success " id="add">Submit</button>
                            </div>

                        </div>


                    </div>
                </div>

            </form>


        </div>
    </div>


<script src= 
"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> 
</script> 
<script>
$(document).ready(function () {
    $('#add').click(function() {
        var question = $("#question").val();
        var answer = $("#option").val();
        console.log(answer);
        localStrage.setItem('question',question);
        localStrage.setItem('answer',answer);
    });
 });

</script>
@endsection

resources/views/task/question/edit.blade.php
@extends('backend.layouts.master')

@section('title','Update question')

@section('content')

    <div class="span9">
        <div class="content">

            @if(Session::has('message'))

                <div class="alert alert-success">{{Session::get('message')}}</div>
            @endif



            <form action="{{route('question.update',[$question->id])}}" method="POST">@csrf
                {{method_field('PUT')}}

                <div class="module">
                    <div class="module-head">
                        <h3>Update Question</h3>
                    </div>


                    <div class="module-body">
                        <div class="control-group">
                            <label class="control-lable" for="name">Choose Quiz</label>
                            <div class="controls">
                                <select name="quiz" class="span8 ">
                                    @foreach(App\Quiz::all() as $quiz)
                                        <option value="{{$quiz->id}}"
                                                @if($quiz->id==$question->quiz_id)selected
                                            @endif

                                        >{{$quiz->name}}</option>
                                    @endforeach

                                </select>
                            </div>
                            @error('question')
                            <span class="invalid-feedback" role="alert">
			        <strong>{{ $message }}</strong>
			    </span>
                            @enderror

                        </div>

                        <div class="control-group">
                            <label class="control-lable" for="name">Question name</label>
                            <div class="controls">
                                <input type="text" name="question" class="span8 @error('name') border-red @enderror" placeholder="name of a quiz" value="{{$question->question}}" >
                            </div>
                            @error('question')
                            <span class="invalid-feedback" role="alert">
			        <strong>{{ $message }}</strong>
			    </span>
                            @enderror

                        </div>

                        <div class="control-group">
                            <label class="control-lable" for="options">Options</label>
                            <div class="controls">
                                @foreach($question->answers as $key=>$answer)
                                    <input type="text" name="options[]" class="span7 "
                                           value="{{$answer->answer}}"
                                           required="" >
                                    <input type="radio" name="correct_answer" value="{{$key}}"@if($answer->is_correct){{'checked'}}@endif

                                    ><span>Is correct answer</span>
                                @endforeach
                            </div>
                            @error('question')
                            <span class="invalid-feedback" role="alert">
			        <strong>{{ $message }}</strong>
			    </span>
                            @enderror

                        </div>


                        <div class="control-group">
                            <div class="controls">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>

                        </div>


                    </div>
                </div>

            </form>


        </div>
    </div>


@endsection

resources/views/task/question/index.blade.php
@extends('layouts.master')

@section('title','create quiz')

@section('content')

<div class="span9">
    <div class="content">
        @if(Session::has('message'))
            <div class="alert alert-success">		
                {{Session::get('message')}}
            </div>
        @endif
        <div class="module">
            <div class="module-head">
                <h3>All Questions</h3>
            </div>

            <div class="module-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Question</th>
                        <th>Created</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(count($questions)>0)
                    @foreach($questions as $key=>$question)
                    <tr>
                        <td>{{$key+1}}</td>
                        <td>{{$question->question}}</td>
                        <td>{{date('F d,Y',strtotime($question->created_at))}}</td>
                        <td>
                            <a href="{{route('question.show',[$question->id])}}"> <button class="btn btn-info">View</button></a>
                        </td>
                        <td>

                            <form id="delete-form{{$question->id}}" method="POST" action="{{route('question.destroy',[$question->id])}}" >@csrf
                                {{method_field('DELETE')}}

                            </form>
                            <a href="#" onclick="if(confirm('Do you want to delete?')){

									  		event.preventDefault();
									  		document.getElementById('delete-form{{$question->id}}').submit()
									  	}else{
									  		event.preventDefault();
									  	}

									  	">
                                <input type="submit" value="Delete" class="btn btn-danger">
                            </a>



                        </td>
                    </tr>
                    @endforeach

                    @else
                    <td>No question to display</td>
                    @endif


                    </tbody>
                </table>
               
            </div>
        </div>

    </div>

</div>
</div>




@endsection

resources/views/task/question/show.blade.php
@extends('layouts.master')

@section('title','create quiz')

@section('content')

    <div class="span9">
        <div class="content">
            @if(Session::has('message'))

                <div class="alert alert-success">            
                    {{Session::get('message')}}
                </div>
            @endif
            <div class="module">
                <div class="module-head">


                </div>

                <div class="module-body">


                    <p><h3  class="heading">{{$question->question}}</h3></p>



                    <div class="module-body table">
                        <table class="table table-message">
                            <tbody>
                            @foreach($question->answers as $key=>$answer)
                                <tr class="read">
                                    <td class="cell-author hidden-phone hidden-tablet">
                                        {{$key+1}}. {{$answer->answer}}
                                        @if($answer->is_correct)
                                            <span class="badge badge-success pull-right">correct</span>
                                        @endif

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                        <a href="{{route('question.index')}}"><button class="btn btn-inverse pull-right">Back</button></a>
                    </div>


                </div>
            </div>

        </div>

    </div>
    </div>

    </div>
    </div>


@endsection